language: node_js
sudo: false
node_js:
  - 16
script:
  - npm i
  - npm run build:doc
  - cp -rf ./assets ./docs
  - $(npm bin)/macaca-ecosystem push --cwd ./docs --branch gh-pages
  - npm run lint
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
